const locations = [
  'Buenos Aires, Argentina',
  'Lima, Peru',
  'Bogota, Colombia',
  'Santiago, Chile',
  'Caracas, Venezuela',
  'Cali, Colombia',
  'Maracaibo, Venezuela',
  'Medellin, Colombia',
  'Guayaquil, Ecuador',
  'Maracay, Venezuela',
  'Asuncion, Paraguay',
  'Cordoba, Argentina',
  'Quito, Ecuador',
  'Valencia, Venezuela',
  'Barranquilla, Colombia',
  'Montevideo, Uruguay',
  'Rosario, Argentina',
  'Cartagena, Colombia',
  'Cochabamba, Bolivia',
  'Mendoza, Argentina',
  'Arequipa, Peru',
  'Callao, Peru',
  'La Paz, Bolivia',
  'Barquisimeto, Venezuela',
  'Trujillo, Peru',
  'Ciudad Guayana, Venezuela',
  'Cucuta, Colombia',
  'La Plata, Argentina',
  'Chiclayo, Peru',
  'Bucaramanga, Colombia',
  'Mar del Plata, Argentina',
  'Quilmes, Argentina',
  'Salta, Argentina',
  'Puente Alto, Chile',
  'San Juan, Argentina',
  'Pereira, Colombia',
  'Iquitos, Peru',
  'Santa Marta, Colombia',
  'Barcelona, Venezuela',
  'Ibague, Colombia',
  'Maturin, Venezuela',
  'Bello, Colombia',
  'Resistencia, Argentina',
  'Pasto, Colombia',
  'Huancayo, Peru',
  'Puerto La Cruz, Venezuela',
  'Petare, Venezuela',
  'Manizales, Colombia',
  'Santiago del Estero, Argentina',
  'Barinas, Venezuela'
]
export default locations
